name: geospatial
channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyter=1.0.0
  - matplotlib=3.2.1
  - geopandas=0.7.0
  - fiona=1.8.13
  - shapely=1.7.0
  - pyproj=2.6.1.post1
  - six=1.14.0
  - rtree=0.9.4
  - descartes=1.1.0
  - folium=0.11.0
